# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(blank=True, default='anon', max_length=50, null=True),
        ),
    ]
